### ISSUE TITLE
Seeking IBus api reference

### ISSUE THREAD

**Issue by dreygur** [titonbarua/sphotik#1]
This is not an issue actually.
I would love to have the IBus api reference for Python

Thanks

**Comment by titonbarua** [comment]
The way gnome ecosystem works is that core developers write their API in C using an object system called `GObject`. Then bindings for other languages are automatically generated using a framework called - `GObject Introspection (gir)`. So, you need to dig a little deeper for documentation for language bindings.

What you seek seems to be available [here](https://lazka.github.io/pgi-docs/#IBus-1.0). Also, here is PyGObject documentation: https://pygobject.readthedocs.io/en/latest/getting_started.html

Cheers.

**Comment by dreygur** [comment]
Thanks for the nice reply.

:heart:
